import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavLink } from "./components/NavLinks";
import { Home, User, Folder, Settings, Mail, FileText } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="sticky top-0 z-50 bg-white/80 backdrop-blur border-b shadow-sm">
          <nav className="flex justify-center gap-6 px-4 py-4 text-sm font-medium text-gray-700">
            <NavLink href="/"><Home size={16} className="inline-block mr-1" />Home</NavLink>
            <NavLink href="/about"><User size={16} className="inline-block mr-1" />About</NavLink>
            <NavLink href="/projects"><Folder size={16} className="inline-block mr-1" />Projects</NavLink>
            <NavLink href="/skills"><Settings size={16} className="inline-block mr-1" />Skills</NavLink>
            <NavLink href="/contact"><Mail size={16} className="inline-block mr-1" />Contact</NavLink>
            <NavLink href="/resume"><FileText size={16} className="inline-block mr-1" />Resume</NavLink>

          </nav>
        </header>

        {/* ✅ wrap children in a container */}
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
